version: '3'
services:
  http:
    image: traefik:2.4.8
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

  backend:
    build: backend
    restart: unless-stopped
    labels:
      - "traefik.http.routers.whoami.rule=Host(`backend.localhost`)"
      - "traefik.enable=true"
